In [2]:
import numpy as np
from numpy import dot as dot
import math
from scipy.optimize import linprog

In [95]:
B = []
B.append([
        [2, 1, 0, 4, 0, 3, 0, 0],
        [0, 4, 0, 3, 1, 1, 3, 2],
        [1, 3, 0, 5, 0, 4, 0, 4]
    ])
B.append([
        [0,     0,   0.5,   2.5,   1,   0,    -2.5, -2],
        [0.5,   0.5, -0.5,  0,     0.5, -0.5, -0.5, -0.5],
        [0.5,   0.5, 0.5,   0,     0.5, 1,     2.5, 4]
    ])
B.append([
        [1, 2, -1.5, 3, -2.5, 0, -1, -0.5],
        [-1.5, -0.5, -1, 2.5, 3.5, 3, -1.5, -0.5],
        [1.5, 2.5, 1, 1, 2.5, 1.5, 3, 0]
    ])
B.append([
        [0.75, 0.5, -1, 0.25, 0.25, 0, 0.25, 0.75],
        [-1, 1, 1, 0.75, 0.75, 0.5, 1, -0.75], 
        [0.5, -0.25, 0.5, 0.75, 0.5, 1.25, -0.75, -0.25],
    ])
B.append([
        [1.5, -1.5, -1.5, 2, 1.5, 0, 0.5, -1.5],
        [-0.5, -2.5, -0.5, -1, -2.5, 2.5, 1, 2],
        [-2.5, 1, -2, 1.5, -2.5, 0.5, 2.5, -2.5]
    ])
B.append([
        [1, 0.25, -0.5, 1.25, 1.25, -0.5, 0.25, -0.75],
        [-1, -0.75, -0.75, 0.5, -0.25, 1.25, 0.25, -0.5],
        [0, 0.75, 0.5, -0.5, -1, 1, -1, 1]
    ])
B = [np.array(np.array([b_i for b_i in b])) for b in B]

c = np.array([
        [-1, -1, -1, -1, -2, 0, -2, -3],
        [0, 60, 80, 0, 0, 0, 40, 0],
        [2, 0, 3, 0, 2, 0, 3, 0],
        [0, 0, 80, 0, 0, 0, 0, 0],
        [0, -2, 1, 2, 0, 0, -2, 1],
        [-4, -2, 6, 0, 4, -2, 60, 2]
    ])

a = np.array(
    [-51.75, -436.75, -33.7813, -303.3750, -41.75]
)


x_0 = np.array([1, 0, 0, 2, 4, 2, 0, 0])

In [102]:
B = []
B.append([
        [2, 1, 0, -4, 0, 3, 0, 0],
        [0, 4, 0, 3, 2, 1, 3, 2],
        [-1, 3, 0, 5, 0, 4, 0, 4]
    ])
B.append([
        [0,     0,   0.5,   0,   -1,   0.5,    0, -2],
        [0.5,   0, -0.5,  0,     0.5, -0.5, -0.5, -0.5],
        [0.5,   0.5, 0.5,   0,     0.5, 0,     2.5, 4]
    ])
B.append([
        [1, 2, -1.5, 3, -2.5, 0, -1, -0.5],
        [-1.5, -0.5, -1, -2.5, 3.5, -3, -1.5, -0.5],
        [1.5, 2.5, -1, 1, 2.5, 1.5, 3, 0]
    ])
B.append([
        [0.75, 0.5, 1, 0.25, 0.25, 0, 0.25, 0.75],
        [-1, 1, 4, 0.75, -0.75, 0.5, 8, -0.75], 
        [0.5, -0.25, 0.5, 0.75, 0.5, 1.25, -0.75, -0.25],
    ])
B.append([
        [2.5, -1.5, -1.5, 2, 1.5, 0, 0.5, -1.5],
        [-0.5, -2.5, -0.5, -6, -2.5, 4.5, 1,1],
        [-2.5, 1, -2, -1.5, -2.5, 0.5, 8.5, -2.5]
    ])
B.append([
        [1, 0.25, -0.5, 0, 1.25, -0.5, 0.25, -0.75],
        [-1, -0.75, -0.75, 0.5, -0.25, -1.25, 0.25, -0.5],
        [0, 0.75, 0.5, -0.5, -1, 1, -1, 1]
    ])
B = [np.array(np.array([b_i for b_i in b])) for b in B]

c = np.array([
        [-2, -4, -1, -1, -2, 0, -3, -3],
        [60, 0, 80, 0, 0, 0, 40, 0],
        [2, 0, 3, 2, 2, 0, 3, 0],
        [0, 0, 80, 0, 0, 0, 0, 0],
        [0, -2, 1, 2, 0, 0, -2, 1],
        [-4, -2, 6, 0, 4, -2, 60, 2]
    ])

a = np.array(
    [-84.25, -158.75, -126.5625, -117.625, -17.8125]
)


x_0 = np.array([0, 3, 1, 1, 0, 2, 0, 0])

In [103]:
def g_i(i, x):  return 0.5 * dot(dot(x, B[i].T), dot(x, B[i].T)) + dot(c[i], x) + a[i - 1]


def f(x): return 0.5 * dot(dot(x, B[0].T), dot(x, B[0].T)) + dot(c[0], x)
    
    
def get_I_0(g_values):
    res = []
    for i in range(len(g_values)):
        if abs(g_values[i]) < 10e-5:
            res.append(i + 1)
            
            
    return res

def get_J_0(x):
    res = []
    for i in range(len(x)):
        if x[i] == 0:
            res.append(i + 1)
            
    return res

In [113]:
print(f'f(x*): {f(x_0)}')
for i in range(1, 6):
    print(f'g_{i}(x*): {g_i(i, x_0)}')

f(x*): 385.0
g_1(x*): 0.0
g_2(x*): -10.0
g_3(x*): 0.0
g_4(x*): -100.0
g_5(x*): 0.0


In [104]:
g_values = [g_i(i, x_0) for i in range(1, 6)]
I_0 = get_I_0(g_values)
J_0 = get_J_0(x_0)

In [114]:
print(f'I_0: {I_0}')
print(f'J_0: {J_0}')

I_0: [1, 3, 5]
J_0: [1, 5, 7, 8]


In [105]:
def mdot(a, b, c): return dot(a, dot(b, c))

In [106]:
def derive_f(x): return dot(dot(x, B[0].T), B[0]) + c[0]


def derive_g_i(x, i): return dot(dot(x, B[i].T), B[i]) + c[i]

In [107]:
d_fx = derive_f(x_0)

In [108]:
print(f'df(x*)/dx: \n {d_fx}')
for i in range(1, 6):
    print(f'df(x*)/dx: \n {derive_g_i(x_0, i)}')

df(x*)/dx: 
 [-14 135  -1 140  32 120  48 119]
df(x*)/dx: 
 [60.25  1.   82.5   0.   -1.25  1.5  45.75  5.75]
df(x*)/dx: 
 [ 41.75  46.75  -7.75  62.5  -29.    48.75  43.5    1.75]
df(x*)/dx: 
 [ -5.1875   9.375  119.25     9.5     -4.375    8.125   68.4375  -5.25  ]
df(x*)/dx: 
 [ -8.75  17.     8.5   23.25   5.25 -22.25  -4.75   0.75]
df(x*)/dx: 
 [ 0.25    4.75   12.25   -4.625   0.0625  8.875  54.3125  9.3125]


In [168]:
costs = derive_f(x_0)
A_ub = [derive_g_i(x_0, i) for i in I_0]
b_ub = [0] * len(x_0)
lb = [-1] * len(x_0)
for j in I_0:
    lb[j - 1] = 0
ub = [1] * len(x_0)
l = linprog(c=costs, A_ub=A_ub, b_ub=[0, 0, 0], bounds=list(zip(lb, ub))).x

In [169]:
print(f'l_0: {l}')

l_0: [ 8.96265560e-01 -1.00000000e+00  1.05313138e-12 -1.00000000e+00
  1.01260698e-12 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00]


In [170]:
print(f'(d_f(x*)/dx, l_0): {dot(d_fx, l)}')

(d_f(x*)/dx, l_0): -574.5477178421232


In [171]:
x_sub = np.array([0] * len(x_0))
delta_x = x_sub - x_0

In [172]:
print(f'x_sub: {x_sub}')
for i in range(1, 6):
    print(f'g_{i}(x_sub): {g_i(i, x_sub)}')

x_sub: [0 0 0 0 0 0 0 0]
g_1(x_sub): -84.25
g_2(x_sub): -158.75
g_3(x_sub): -126.5625
g_4(x_sub): -117.625
g_5(x_sub): -17.8125


In [173]:
alpha = 1

In [174]:
dot(d_fx, l) + alpha * dot(d_fx, delta_x)

-1358.5477178421233

In [183]:
def x_tf(t, x_0, alpha, delta_x): return x_0 + t * alpha * delta_x

In [188]:
t = 0.5
x_t = x_tf(t, x_0, alpha, delta_x)

In [189]:
x_t

array([0. , 1.5, 0.5, 0.5, 0. , 1. , 0. , 0. ])

In [190]:
print(f't = {t}, alpha = 1')
print(f'x_t: {x_t}')
for i in range(1, 6):
    print(f'g_{i}(x(t)): {g_i(i, x_t)}')

t = 0.5, alpha = 1
x_t: [0.  1.5 0.5 0.5 0.  1.  0.  0. ]
g_1(x(t)): -43.1875
g_2(x(t)): -120.3125
g_3(x(t)): -74.921875
g_4(x(t)): -113.96875
g_5(x(t)): -14.359375


In [179]:
f(x_sub)

0.0

In [153]:
I_0, J_0

([1, 3, 5], [1, 5, 7, 8])

In [117]:
[g_i(i, x_sub) for i in range(1, 6)]

[-84.25, -158.75, -126.5625, -117.625, -17.8125]